# Generated by Django 5.2.4 on 2025-08-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CtThanhtoanDichvu',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('tientruocthue', models.FloatField(blank=True, db_column='TienTruocThue', null=True)),
                ('thue', models.FloatField(blank=True, db_column='Thue', null=True)),
                ('tiensauthue', models.FloatField(blank=True, db_column='TienSauThue', null=True)),
                ('donvitinh', models.CharField(blank=True, db_column='DonViTinh', null=True)),
                ('chisocu', models.FloatField(blank=True, db_column='ChiSoCu', null=True)),
                ('chisomoi', models.FloatField(blank=True, db_column='ChiSoMoi', null=True)),
                ('heso', models.IntegerField(blank=True, db_column='HeSo', null=True)),
                ('dongia', models.FloatField(blank=True, db_column='DonGia', null=True)),
                ('sosudung', models.FloatField(blank=True, db_column='SoSuDung', null=True)),
                ('loaithue', models.BigIntegerField(blank=True, db_column='LoaiThue', null=True)),
                ('tendichvu', models.CharField(blank=True, db_column='TenDichVu', null=True)),
            ],
            options={
                'db_table': 'CT_ThanhToan_DichVu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Dichvu',
            fields=[
                ('id_dichvu', models.BigAutoField(db_column='Id_DichVu', primary_key=True, serialize=False)),
                ('tendichvu', models.CharField(blank=True, db_column='TenDichVu', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
                ('ngayghi', models.DateField(blank=True, db_column='NgayGhi', null=True)),
            ],
            options={
                'db_table': 'DichVu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hopdong',
            fields=[
                ('id_hopdong', models.BigAutoField(db_column='Id_HopDong', primary_key=True, serialize=False)),
                ('tencongty', models.CharField(blank=True, db_column='TenCongTy', null=True)),
                ('sohd', models.CharField(blank=True, db_column='SoHD', null=True)),
                ('kythanhtoan', models.BigIntegerField(blank=True, db_column='KyThanhToan', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
                ('ngaytaohopdong', models.DateField(blank=True, db_column='NgayTaoHopDong', null=True)),
                ('tiencoc', models.FloatField(blank=True, db_column='TienCoc', null=True)),
                ('ngayketthuc', models.DateField(blank=True, db_column='NgayKetThuc', null=True)),
                ('trangthai', models.SmallIntegerField(blank=True, db_column='TrangThai', null=True)),
                ('ngaybatdautinhtien', models.DateField(blank=True, db_column='NgayBatDauTinhTien', null=True)),
            ],
            options={
                'db_table': 'HopDong',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HopdongDichvu',
            fields=[
                ('id_hopdongdichvu', models.BigAutoField(db_column='Id_HopDongDichVu', primary_key=True, serialize=False)),
                ('dongia', models.FloatField(blank=True, db_column='DonGia', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
                ('donvitinh', models.CharField(blank=True, db_column='DonViTinh', null=True)),
            ],
            options={
                'db_table': 'HopDong_DichVu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HopdongNhaxuong',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dientich', models.FloatField(blank=True, db_column='DienTich', null=True)),
                ('dongia', models.FloatField(blank=True, db_column='DonGia', null=True)),
                ('ngaybatdau', models.DateField(blank=True, db_column='NgayBatDau', null=True)),
                ('ngayketthuc', models.DateField(blank=True, db_column='NgayKetThuc', null=True)),
                ('loaithanhtoan', models.CharField(blank=True, db_column='LoaiThanhToan', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loaidichvu',
            fields=[
                ('id_loaidichvu', models.BigAutoField(db_column='Id_LoaiDichVu', primary_key=True, serialize=False)),
                ('tenloaidichvu', models.CharField(db_column='TenLoaiDichVu')),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'LoaiDichVu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Loaitaisan',
            fields=[
                ('id_loaitaisan', models.BigAutoField(db_column='Id_LoaiTaiSan', primary_key=True, serialize=False)),
                ('tenloaitaisan', models.CharField(db_column='TenLoaiTaiSan')),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'LoaiTaiSan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Taisan',
            fields=[
                ('id_taisan', models.BigAutoField(db_column='Id_TaiSan', primary_key=True, serialize=False)),
                ('tentaisan', models.CharField(blank=True, db_column='TenTaiSan', null=True)),
                ('ngayghitang', models.DateField(blank=True, db_column='NgayGhiTang', null=True)),
                ('thoigiansudung', models.CharField(blank=True, db_column='ThoiGianSuDung', null=True)),
                ('nguyengia', models.FloatField(blank=True, db_column='NguyenGia', null=True)),
                ('chuthich', models.CharField(blank=True, db_column='ChuThich', null=True)),
            ],
            options={
                'db_table': 'TaiSan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThanhtoanDichvu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('thoigiantao', models.DateTimeField(blank=True, db_column='ThoigianTao', null=True)),
                ('sotbdv', models.CharField(blank=True, db_column='SoTBDV', null=True)),
                ('giamtru', models.FloatField(blank=True, db_column='GiamTru', null=True)),
                ('tongtientruocthue', models.FloatField(blank=True, db_column='TongTienTruocThue', null=True)),
                ('tongtiensauthue', models.FloatField(blank=True, db_column='TongTienSauThue', null=True)),
            ],
            options={
                'db_table': 'ThanhToan_DichVu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ThanhtoanNhaxuong',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ngaytao', models.DateTimeField(db_column='NgayTao')),
                ('tongtien', models.FloatField(blank=True, db_column='TongTien', null=True)),
            ],
            options={
                'db_table': 'ThanhToan_NhaXuong',
                'managed': False,
            },
        ),
    ]
