# Generated by Django 5.2.4 on 2025-11-06 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dich_vu_dien_nuoc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ctthanhtoandichvu',
            table='"public"."CT_ThanhToan_DichVu"',
        ),
        migrations.AlterModelTable(
            name='dichvu',
            table='"public"."DichVu"',
        ),
        migrations.AlterModelTable(
            name='hopdong',
            table='"public"."HopDong"',
        ),
        migrations.AlterModelTable(
            name='hopdongdichvu',
            table='"public"."HopDong_DichVu"',
        ),
        migrations.AlterModelTable(
            name='loaidichvu',
            table='"public"."LoaiDichVu"',
        ),
        migrations.AlterModelTable(
            name='loaitaisan',
            table='"public"."LoaiTaiSan"',
        ),
        migrations.AlterModelTable(
            name='taisan',
            table='"public"."TaiSan"',
        ),
        migrations.AlterModelTable(
            name='thanhtoandichvu',
            table='"public"."ThanhToan_DichVu"',
        ),
        migrations.AlterModelTable(
            name='thanhtoannhaxuong',
            table='"public"."ThanhToan_NhaXuong"',
        ),
    ]
